version: "1.0"
info:
  model: int-scaffold
packages:
- name: FR_STT_SandboxProject
  gitServerName: sttlab_github
  gitUrl: https://github.com/sttlab-tech
  gitUsername: sttlab-tech
  gitBranch: main
